name: dev-pipeline

on:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  actions: read
  contents: read

jobs:
  dev-pipeline:
    # environment: dev

    name: 'Deploy to Dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up NodeJS LTS
        uses: ./.github/actions/setup-node

      - name: Install dependecies
        uses: ./.github/actions/install-dependencies
        with:
          cwd: '.'
          enable-corepack: false
          cache-node-modules: true
          cache-install-state: true

      - name:
          Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Fetch commits for nx affected
        uses: ./.github/actions/get-affected-fetch

      - name: Linting
        run: npx nx affected -t lint --base=${{ github.ref_name }} --parallel


      - name: Build Backend Services
        run: npx nx affected -t build --base=${{ github.ref_name }} --parallel
